import { Category } from './types';

export const preambleQuestions = [
  {
    id: 'companion_name',
    text: "What is your name?",
    answerType: 'freetext' as const,
    placeholder: 'Your full name',
    summaryKey: 'companionName',
    section: 'About You',
  },
  {
    id: 'relationship',
    text: "What is your relationship to the patient?",
    answerType: 'choice' as const,
    choices: ['Spouse / Partner', 'Parent', 'Adult child', 'Sibling', 'Friend', 'Caregiver', 'Other'],
    summaryKey: 'relationship',
    section: 'About You',
  },
  {
    id: 'patient_name',
    text: "What is the patient's first name? (So we can use it in the summary)",
    answerType: 'freetext' as const,
    placeholder: 'Their first name',
    summaryKey: 'patientName',
    section: 'About You',
  },
  {
    id: 'patient_age',
    text: "How old are they?",
    answerType: 'freetext' as const,
    placeholder: 'e.g., "42", "8 months", "about 70"',
    summaryKey: 'patientAge',
    section: 'About You',
  },
  {
    id: 'allergies',
    text: "Do you know of any medication allergies they have?",
    answerType: 'freetext' as const,
    placeholder: 'e.g., "Penicillin" or "None that I know of"',
    summaryKey: 'allergies',
    section: 'About You',
    skippable: true,
  },
  {
    id: 'last_oral_intake',
    text: "When did they last eat or drink anything?",
    answerType: 'freetext' as const,
    placeholder: 'e.g., "Dinner around 7pm" — this matters if surgery is needed',
    summaryKey: 'lastOralIntake',
    section: 'About You',
    skippable: true,
  },
];

export const categories: Category[] = [
  {
    id: 'trauma',
    label: "They fell, were in an accident, or got hurt",
    description: 'Falls, car accidents, injuries — especially with unclear mechanism or unwitnessed',
    icon: '🩹',
    estimateMinutes: 13,
    questions: [
      {
        id: 'trauma_what_happened',
        text: "What happened?",
        answerType: 'freetext',
        placeholder: 'Describe the accident, fall, or injury',
        summaryKey: 'what_happened',
        section: 'What happened',
      },
      {
        id: 'trauma_witnessed',
        text: "Did you see it happen?",
        answerType: 'yesno',
        branches: { 'Yes': 'trauma_describe_witnessed', 'No': 'trauma_found' },
        summaryKey: 'witnessed',
        section: 'What happened',
      },
      {
        id: 'trauma_describe_witnessed',
        text: "Describe exactly what you saw — how they fell, what they hit, what position they landed in.",
        answerType: 'freetext',
        placeholder: 'What you saw happen',
        next: 'trauma_when',
        summaryKey: 'witnessed_description',
        section: 'What happened',
      },
      {
        id: 'trauma_found',
        text: "How did you find them? What did the scene look like?",
        answerType: 'freetext',
        placeholder: 'What you found when you arrived',
        summaryKey: 'found_description',
        section: 'What happened',
      },
      {
        id: 'trauma_when',
        text: "When did it happen — or when did you find them?",
        answerType: 'freetext',
        placeholder: 'e.g., "About 2 hours ago" or "I found them at 6am but it may have happened overnight"',
        summaryKey: 'when_happened',
        section: 'Timeline',
      },
      {
        id: 'trauma_mechanism',
        text: "How serious was the impact?",
        answerType: 'choice',
        choices: [
          'A fall from standing height or lower',
          'A fall from more than 3 feet or more than 5 stairs',
          'Struck by or thrown from a vehicle',
          'A high-speed crash',
          "Something else / I'm not sure",
        ],
        summaryKey: 'mechanism',
        section: 'Mechanism of injury',
      },
      {
        id: 'trauma_consciousness',
        text: "Did they lose consciousness at any point?",
        answerType: 'choice',
        choices: ['Yes — I saw them unconscious', 'I think so but I\'m not sure', 'No — they were awake the whole time', 'I don\'t know — I wasn\'t there when it happened'],
        summaryKey: 'consciousness',
        section: 'Consciousness and alertness',
      },
      {
        id: 'trauma_alertness_now',
        text: "How alert are they right now?",
        answerType: 'choice',
        choices: ['Fully alert and talking normally', 'Awake but confused or groggy', 'Drowsy — hard to keep awake', 'Not responding normally'],
        urgentAlert: {
          on: ['Drowsy — hard to keep awake', 'Not responding normally'],
          message: 'Declining alertness after an injury needs immediate attention. Tell the triage nurse now.',
        },
        summaryKey: 'current_alertness',
        section: 'Consciousness and alertness',
      },
      {
        id: 'trauma_amnesia',
        text: "Do they remember what happened — or is there a gap in their memory?",
        answerType: 'choice',
        choices: [
          'They remember everything',
          "There's a gap — they don't remember the event",
          'Hard to tell',
          "I don't know",
        ],
        summaryKey: 'memory_of_event',
        section: 'Consciousness and alertness',
      },
      {
        id: 'trauma_head_hit',
        text: "Did they hit their head — or could they have?",
        answerType: 'choice',
        choices: ['Yes — definitely', 'Possibly — I\'m not sure', 'No — I\'m confident they didn\'t'],
        summaryKey: 'head_impact',
        section: 'Mechanism of injury',
      },
      {
        id: 'trauma_intoxication',
        text: "Could they have been drinking alcohol or using drugs when it happened?",
        answerType: 'choice',
        choices: ['Yes', 'No', "I don't know"],
        summaryKey: 'intoxication',
        section: 'Mechanism of injury',
      },
      {
        id: 'trauma_vomiting',
        text: "Have they vomited since the injury (especially more than once), or complained of a worsening headache?",
        answerType: 'yesno',
        summaryKey: 'post_injury_vomiting',
        section: 'Mechanism of injury',
      },
      {
        id: 'trauma_movement',
        text: "What can they move and what can't they move?",
        answerType: 'freetext',
        placeholder: 'e.g., "She can move her arms but can\'t put weight on her right leg"',
        summaryKey: 'movement_ability',
        section: 'What they can and can\'t move',
      },
      {
        id: 'trauma_pain_location',
        text: "Where are they saying it hurts?",
        answerType: 'freetext',
        placeholder: 'Where they say the pain is',
        summaryKey: 'pain_location',
        section: 'What they can and can\'t move',
      },
      {
        id: 'trauma_neck_back',
        text: "Have they complained of neck or back pain since the injury?",
        answerType: 'yesno',
        summaryKey: 'neck_back_pain',
        section: 'What they can and can\'t move',
      },
      {
        id: 'trauma_bleeding',
        text: "Is there any bleeding or a visible wound?",
        answerType: 'yesno',
        branches: { 'Yes': 'trauma_bleeding_detail', 'No': 'trauma_blood_thinners' },
        summaryKey: 'bleeding_present',
        section: 'Injuries you can see',
      },
      {
        id: 'trauma_bleeding_detail',
        text: "Where is the bleeding, and how much? Has it stopped or slowed?",
        answerType: 'freetext',
        placeholder: 'Location, how heavy, and whether it has stopped',
        summaryKey: 'bleeding_detail',
        section: 'Injuries you can see',
      },
      {
        id: 'trauma_blood_thinners',
        text: "Are they on blood thinners or any medications that affect bleeding?",
        answerType: 'choice',
        choices: ['Yes', 'No', "I don't know"],
        summaryKey: 'blood_thinners',
        section: 'Prior conditions that matter',
      },
      {
        id: 'trauma_prior_conditions',
        text: "Do they have any medical conditions the provider should know about?",
        answerType: 'freetext',
        placeholder: 'e.g., "Osteoporosis" or "Diabetes" or "None that I know of"',
        summaryKey: 'prior_conditions',
        section: 'Prior conditions that matter',
        skippable: true,
      },
      {
        id: 'trauma_concern',
        text: "What are you most worried about?",
        answerType: 'freetext',
        placeholder: 'Your biggest concern',
        summaryKey: 'primary_concern',
        section: 'Your concern',
      },
    ],
  },
  {
    id: 'abdominal',
    label: "Stomach pain or vomiting",
    description: "Abdominal pain, vomiting, or can't keep anything down",
    icon: '🤢',
    estimateMinutes: 11,
    questions: [
      {
        id: 'abd_what_happened',
        text: "In your own words, what's wrong?",
        answerType: 'freetext',
        placeholder: 'Describe what brought you in',
        summaryKey: 'what_happened',
        section: 'What happened',
      },
      {
        id: 'abd_when_started',
        text: "When did it start?",
        answerType: 'freetext',
        placeholder: 'e.g., "Last night after dinner" or "Three days ago, getting worse"',
        summaryKey: 'onset_time',
        section: 'Timeline',
      },
      {
        id: 'abd_progression',
        text: "Since it started, has it changed?",
        answerType: 'choice',
        choices: ['Getting worse', 'About the same', 'Comes in waves', 'Getting better', "I'm not sure"],
        summaryKey: 'progression',
        section: 'Timeline',
      },
      {
        id: 'abd_pain_location',
        text: "Where is the pain? Point to it if they can.",
        answerType: 'choice',
        choices: [
          'Upper right — under the ribs',
          'Upper middle — stomach area',
          'Lower right',
          'Lower left',
          'All over',
          'It started one place and moved',
          "No real pain — it's mainly vomiting",
        ],
        summaryKey: 'pain_location',
        section: 'The pain',
      },
      {
        id: 'abd_severity',
        text: "How bad is the pain?",
        answerType: 'choice',
        choices: [
          'Mild — uncomfortable but functioning',
          'Moderate — clearly in pain',
          "Severe — the worst pain they've ever had",
          'No real pain',
        ],
        summaryKey: 'pain_severity',
        section: 'The pain',
      },
      {
        id: 'abd_tender',
        text: "Does it hurt when their belly is touched — or does the belly feel rigid and hard?",
        answerType: 'yesno',
        summaryKey: 'abdomen_tender',
        section: 'The pain',
      },
      {
        id: 'abd_vomiting',
        text: "Have they been vomiting?",
        answerType: 'yesno',
        branches: { 'Yes': 'abd_vomit_detail', 'No': 'abd_blood_stool' },
        summaryKey: 'vomiting',
        section: 'Vomiting and other symptoms',
      },
      {
        id: 'abd_vomit_detail',
        text: "How many times, and can they keep anything down?",
        answerType: 'freetext',
        placeholder: 'e.g., "Five times since last night, not even water stays down"',
        summaryKey: 'vomit_detail',
        section: 'Vomiting and other symptoms',
      },
      {
        id: 'abd_vomit_blood',
        text: "Was there any blood in the vomit — or did it look dark, like coffee grounds?",
        answerType: 'yesno',
        summaryKey: 'vomit_blood',
        section: 'Vomiting and other symptoms',
      },
      {
        id: 'abd_blood_stool',
        text: "Any blood in their stool, or black tar-like stools?",
        answerType: 'yesno',
        summaryKey: 'blood_in_stool',
        section: 'Vomiting and other symptoms',
      },
      {
        id: 'abd_fever',
        text: "Have they had a fever?",
        answerType: 'yesno',
        summaryKey: 'fever',
        section: 'Vomiting and other symptoms',
      },
      {
        id: 'abd_red_flags',
        text: "Do any of these apply? Select all that apply.",
        answerType: 'multichoice',
        choices: [
          "They can't pee",
          "They can't poo or pass gas",
          'They have diabetes and are vomiting',
          'None of these',
        ],
        summaryKey: 'red_flags',
        section: 'Vomiting and other symptoms',
      },
      {
        id: 'abd_pregnancy',
        text: "Is there any chance they could be pregnant?",
        answerType: 'choice',
        choices: ['Yes — possibly', 'No', 'Not applicable'],
        summaryKey: 'pregnancy_possible',
        section: 'Medical context',
      },
      {
        id: 'abd_history',
        text: "Any history of abdominal surgery, gallstones, ulcers, or episodes like this before?",
        answerType: 'freetext',
        placeholder: 'e.g., "Gallbladder removed in 2019" or "None that I know of"',
        summaryKey: 'abdominal_history',
        section: 'Medical context',
        skippable: true,
      },
      {
        id: 'abd_medications',
        text: "Are they on any medications? (Especially blood thinners, aspirin, or ibuprofen-type pain relievers)",
        answerType: 'freetext',
        placeholder: 'List what you know, or "I\'m not sure"',
        summaryKey: 'medications',
        section: 'Medical context',
        skippable: true,
      },
      {
        id: 'abd_concern',
        text: "What worries you most right now?",
        answerType: 'freetext',
        placeholder: 'Your biggest concern',
        summaryKey: 'primary_concern',
        section: 'Your concern',
      },
    ],
  },
  {
    id: 'cardiac',
    label: "Chest pain, heart racing, or passed out",
    description: 'Chest pain, palpitations, fainting, or sudden shortness of breath',
    icon: '❤️',
    estimateMinutes: 12,
    questions: [
      {
        id: 'cardiac_what_happened',
        text: "In your own words, what happened?",
        answerType: 'freetext',
        placeholder: 'Describe what you saw',
        summaryKey: 'what_happened',
        section: 'What happened',
      },
      {
        id: 'cardiac_consciousness',
        text: "Did they lose consciousness or pass out?",
        answerType: 'yesno',
        branches: { 'Yes': 'cardiac_unconscious_duration', 'No': 'cardiac_when_started' },
        summaryKey: 'lost_consciousness',
        section: 'What happened',
      },
      {
        id: 'cardiac_unconscious_duration',
        text: "How long were they unconscious?",
        answerType: 'freetext',
        placeholder: 'e.g., "About 30 seconds" or "A few minutes"',
        summaryKey: 'unconscious_duration',
        section: 'What happened',
      },
      {
        id: 'cardiac_when_started',
        text: "When did the symptoms start? A clock time helps the provider most.",
        answerType: 'freetext',
        placeholder: 'e.g., "Around 7:40 tonight" or "About an hour ago, at dinner"',
        summaryKey: 'onset_time',
        section: 'Timeline',
      },
      {
        id: 'cardiac_activity',
        text: "What were they doing when it started?",
        answerType: 'choice',
        choices: ['Resting or sitting', 'Walking or light activity', 'Exercise or heavy exertion', 'Sleeping — it woke them up', 'Eating', 'Emotionally stressed'],
        summaryKey: 'onset_activity',
        section: 'Timeline',
      },
      {
        id: 'cardiac_changing',
        text: "Has the pain or symptom changed since it started?",
        answerType: 'choice',
        choices: ['Getting worse', 'About the same', 'Comes and goes', 'Getting better', "I'm not sure"],
        summaryKey: 'progression',
        section: 'Timeline',
      },
      {
        id: 'cardiac_appearance',
        text: "What do they look like right now? Select everything you notice.",
        answerType: 'multichoice',
        choices: ['Pale or gray', 'Sweating', 'Clutching their chest', 'Short of breath', 'Anxious or restless', 'Calm — but something seems wrong', 'None of these — they look normal'],
        summaryKey: 'appearance',
        section: 'What you observed',
      },
      {
        id: 'cardiac_pain_location',
        text: "If they have pain, where is it? Have they told you?",
        answerType: 'freetext',
        placeholder: 'e.g., "Center of chest" or "Left arm and jaw" or "They haven\'t said"',
        summaryKey: 'pain_location',
        section: 'What you observed',
        skippable: true,
      },
      {
        id: 'cardiac_pain_radiation',
        text: "Does the pain spread anywhere — to the jaw, left arm, shoulder, back, or between the shoulder blades?",
        answerType: 'yesno',
        branches: { 'Yes': 'cardiac_radiation_where', 'No': 'cardiac_prior_heart' },
        summaryKey: 'pain_radiates',
        section: 'What you observed',
      },
      {
        id: 'cardiac_radiation_where',
        text: "Where does the pain spread to?",
        answerType: 'freetext',
        placeholder: 'e.g., "Down the left arm" or "Into the jaw and back"',
        summaryKey: 'radiation_location',
        section: 'What you observed',
      },
      {
        id: 'cardiac_prior_heart',
        text: "Do they have any known heart problems?",
        answerType: 'freetext',
        placeholder: 'e.g., "High blood pressure" or "Had a stent two years ago" or "None that I know of"',
        summaryKey: 'prior_cardiac',
        section: 'Risk factors',
      },
      {
        id: 'cardiac_medications',
        text: "Are they on any heart or blood pressure medications?",
        answerType: 'freetext',
        placeholder: 'List what you know, or "I\'m not sure"',
        summaryKey: 'medications',
        section: 'Risk factors',
        skippable: true,
      },
      {
        id: 'cardiac_family',
        text: "Is there a family history of heart attacks or heart disease?",
        answerType: 'yesno',
        summaryKey: 'family_history',
        section: 'Risk factors',
        skippable: true,
      },
      {
        id: 'cardiac_pe_risk',
        text: "In the past month, has any of this applied to them? Select all that apply.",
        answerType: 'multichoice',
        choices: [
          'Surgery or a hospital stay',
          'A long car or plane trip',
          'Mostly bedridden or immobile',
          'Swelling or pain in one leg',
          'A previous blood clot (DVT or PE)',
          'Cancer, or cancer treatment in the past 6 months',
          'Birth control pills or hormone therapy',
          'None of these',
          "I'm not sure",
        ],
        summaryKey: 'clot_risk_factors',
        section: 'Risk factors',
      },
      {
        id: 'cardiac_happened_before',
        text: "Has anything like this happened before?",
        answerType: 'yesno',
        branches: { 'Yes': 'cardiac_prior_detail', 'No': 'cardiac_anything_else' },
        summaryKey: 'happened_before',
        section: 'Risk factors',
      },
      {
        id: 'cardiac_prior_detail',
        text: "What happened last time? Was it evaluated?",
        answerType: 'freetext',
        placeholder: 'What happened and what was found',
        summaryKey: 'prior_episode_detail',
        section: 'Risk factors',
      },
      {
        id: 'cardiac_anything_else',
        text: "Is there anything else you think the provider should know?",
        answerType: 'freetext',
        placeholder: 'Anything that seems relevant',
        summaryKey: 'additional',
        section: 'Anything else',
        skippable: true,
      },
    ],
  },
  {
    id: 'breathing',
    label: "They're struggling to breathe",
    description: 'Shortness of breath, wheezing, choking, or breathing that looks wrong',
    icon: '🫁',
    estimateMinutes: 9,
    questions: [
      {
        id: 'br_what_happened',
        text: "In your own words, what's happening with their breathing?",
        answerType: 'freetext',
        placeholder: 'Describe what you see and hear',
        summaryKey: 'what_happened',
        section: 'What happened',
      },
      {
        id: 'br_onset',
        text: "How quickly did this come on?",
        answerType: 'choice',
        choices: ['Suddenly — within minutes', 'Over a few hours', 'Over days', "I'm not sure"],
        summaryKey: 'onset_speed',
        section: 'Timeline',
      },
      {
        id: 'br_choking',
        text: "Could they have choked on something — food or an object?",
        answerType: 'yesno',
        branches: { 'Yes': 'br_choking_detail', 'No': 'br_appearance' },
        summaryKey: 'possible_choking',
        section: 'What happened',
      },
      {
        id: 'br_choking_detail',
        text: "What were they eating or doing, and what happened?",
        answerType: 'freetext',
        placeholder: 'What they may have choked on and what you saw',
        summaryKey: 'choking_detail',
        section: 'What happened',
      },
      {
        id: 'br_appearance',
        text: "What do you see right now? Select all that apply.",
        answerType: 'multichoice',
        choices: [
          'Breathing fast',
          "Can't speak in full sentences",
          'Lips or fingertips look bluish',
          'Wheezing or noisy breathing',
          'Using neck or chest muscles to breathe',
          "Sitting upright — can't lie down",
          'None of these',
        ],
        urgentAlert: {
          on: ['Lips or fingertips look bluish', "Can't speak in full sentences"],
          message: 'Bluish lips or being unable to speak in full sentences are signs of severe breathing distress. Tell the triage nurse now.',
        },
        summaryKey: 'appearance',
        section: 'What you observed',
      },
      {
        id: 'br_chest_pain',
        text: "Are they also having chest pain?",
        answerType: 'yesno',
        summaryKey: 'chest_pain',
        section: 'What you observed',
      },
      {
        id: 'br_fever_cough',
        text: "Have they had a fever or a cough in the past few days?",
        answerType: 'yesno',
        summaryKey: 'fever_cough',
        section: 'What you observed',
      },
      {
        id: 'br_cough_blood',
        text: "Have they coughed up any blood?",
        answerType: 'yesno',
        summaryKey: 'coughing_blood',
        section: 'What you observed',
      },
      {
        id: 'br_lung_history',
        text: "Do they have asthma, COPD, or other lung problems? If they used an inhaler, did it help?",
        answerType: 'freetext',
        placeholder: 'e.g., "Asthma — used her inhaler twice with no relief" or "None"',
        summaryKey: 'lung_history',
        section: 'Medical context',
      },
      {
        id: 'br_pe_risk',
        text: "In the past month, has any of this applied to them? Select all that apply.",
        answerType: 'multichoice',
        choices: [
          'Surgery or a hospital stay',
          'A long car or plane trip',
          'Mostly bedridden or immobile',
          'Swelling or pain in one leg',
          'A previous blood clot (DVT or PE)',
          'Cancer, or cancer treatment in the past 6 months',
          'Birth control pills or hormone therapy',
          'None of these',
          "I'm not sure",
        ],
        summaryKey: 'clot_risk_factors',
        section: 'Medical context',
      },
      {
        id: 'br_medications',
        text: "Are they on any medications?",
        answerType: 'freetext',
        placeholder: 'List what you know, or "I\'m not sure"',
        summaryKey: 'medications',
        section: 'Medical context',
        skippable: true,
      },
      {
        id: 'br_concern',
        text: "What worries you most right now?",
        answerType: 'freetext',
        placeholder: 'Your biggest concern',
        summaryKey: 'primary_concern',
        section: 'Your concern',
      },
    ],
  },
  {
    id: 'pediatric',
    label: "My child is sick or hurt",
    description: 'For parents bringing a child to the ER',
    icon: '👶',
    estimateMinutes: 12,
    questions: [
      {
        id: 'ped_what_happened',
        text: "In your own words, what happened or what's wrong?",
        answerType: 'freetext',
        placeholder: 'Describe what brought you in',
        summaryKey: 'what_happened',
        section: 'What happened',
      },
      {
        id: 'ped_when_noticed',
        text: "When did you first notice something was wrong?",
        answerType: 'freetext',
        placeholder: 'e.g., "This morning when she woke up" or "About two hours ago"',
        summaryKey: 'when_noticed',
        section: 'Timeline',
      },
      {
        id: 'ped_different',
        text: "Is this different from how they normally act? What's changed?",
        answerType: 'freetext',
        placeholder: 'What\'s different from their usual behavior',
        summaryKey: 'behavior_change',
        section: 'What you\'ve observed',
      },
      {
        id: 'ped_cant_do',
        text: "Can they do things they could do yesterday? (Walk, crawl, hold things, talk normally)",
        answerType: 'freetext',
        placeholder: 'What they can and can\'t do compared to normal',
        summaryKey: 'functional_change',
        section: 'What you\'ve observed',
      },
      {
        id: 'ped_eating',
        text: "How are they eating and drinking?",
        answerType: 'choice',
        choices: ['Normal', 'Less than usual', 'Refusing food or drink', 'Vomiting what they eat or drink'],
        summaryKey: 'eating_status',
        section: 'Eating, drinking, sleeping',
      },
      {
        id: 'ped_sleeping',
        text: "How are they sleeping?",
        answerType: 'choice',
        choices: ['Normal', 'More sleepy than usual', 'Can\'t sleep / restless', 'Hard to wake up'],
        summaryKey: 'sleeping_status',
        section: 'Eating, drinking, sleeping',
      },
      {
        id: 'ped_dehydration',
        text: "Have you noticed any of these? Select all that apply.",
        answerType: 'multichoice',
        choices: [
          'Fewer wet diapers or urinating less than usual',
          'No tears when crying',
          'Dry mouth or lips',
          'Sunken eyes or sunken soft spot',
          'None of these',
        ],
        summaryKey: 'dehydration_signs',
        section: 'Eating, drinking, sleeping',
      },
      {
        id: 'ped_fever',
        text: "Do they have a fever? Have you taken their temperature?",
        answerType: 'freetext',
        placeholder: 'e.g., "101.5°F an hour ago" or "They feel warm but I haven\'t checked"',
        summaryKey: 'fever',
        section: 'Symptoms',
      },
      {
        id: 'ped_rash',
        text: "Do they have a rash — especially if they also have a fever?",
        answerType: 'yesno',
        branches: { 'Yes': 'ped_rash_detail', 'No': 'ped_meningitis_signs' },
        summaryKey: 'rash_present',
        section: 'Symptoms',
      },
      {
        id: 'ped_rash_detail',
        text: "What does the rash look like? Where is it? Does it fade when you press on it?",
        answerType: 'freetext',
        placeholder: 'Describe the rash — color, location, whether it blanches',
        summaryKey: 'rash_detail',
        section: 'Symptoms',
      },
      {
        id: 'ped_meningitis_signs',
        text: "Have you noticed any of these? Select all that apply.",
        answerType: 'multichoice',
        choices: [
          'A stiff neck',
          'Bothered by bright lights',
          'A bulging soft spot on their head (babies)',
          'An unusual, high-pitched cry',
          'Unusually cold hands and feet',
          'None of these',
        ],
        urgentAlert: {
          on: ['A stiff neck', 'A bulging soft spot on their head (babies)'],
          message: 'A stiff neck or bulging soft spot — especially with a fever — needs urgent attention. Tell the triage nurse now.',
        },
        summaryKey: 'meningitis_signs',
        section: 'Symptoms',
      },
      {
        id: 'ped_breathing',
        text: "Are they breathing normally? Look for fast breathing, nostrils flaring, ribs showing with each breath, or grunting.",
        answerType: 'choice',
        choices: ['Breathing looks normal', 'Breathing faster than usual', 'Visibly working hard to breathe', 'Making unusual sounds when breathing', "I'm not sure"],
        summaryKey: 'breathing_status',
        section: 'Symptoms',
      },
      {
        id: 'ped_ingestion',
        text: "Is there any chance they swallowed something — medications, cleaning products, batteries, magnets, or anything else?",
        answerType: 'choice',
        choices: [
          'Yes — I know or strongly suspect it',
          "It's possible — they were unsupervised for a while",
          'No — very unlikely',
        ],
        summaryKey: 'possible_ingestion',
        section: 'Symptoms',
      },
      {
        id: 'ped_tried',
        text: "What have you already tried? (Medications, cooling, fluids, etc.)",
        answerType: 'freetext',
        placeholder: 'What you\'ve done so far',
        summaryKey: 'tried_already',
        section: 'What you\'ve tried',
        skippable: true,
      },
      {
        id: 'ped_medications',
        text: "Are they on any medications or do they have any known medical conditions?",
        answerType: 'freetext',
        placeholder: 'Medications and conditions, or "None"',
        summaryKey: 'medications_conditions',
        section: 'Medical context',
        skippable: true,
      },
      {
        id: 'ped_daycare',
        text: "Are they in daycare or school? Is anything going around?",
        answerType: 'freetext',
        placeholder: 'e.g., "Yes, strep is going around her class" or "Not in daycare"',
        summaryKey: 'daycare_context',
        section: 'Medical context',
        skippable: true,
      },
      {
        id: 'ped_concern',
        text: "What is your biggest concern — the thing you most want the provider to check?",
        answerType: 'freetext',
        placeholder: 'What worries you most',
        summaryKey: 'primary_concern',
        section: 'Your concern',
      },
    ],
  },
  {
    id: 'elderly',
    label: "My parent isn't acting right",
    description: 'For adult children accompanying an elderly parent',
    icon: '🤍',
    estimateMinutes: 13,
    questions: [
      {
        id: 'elder_what_changed',
        text: "What made you bring them in today? What changed?",
        answerType: 'freetext',
        placeholder: 'Describe what prompted the visit',
        summaryKey: 'what_changed',
        section: 'What changed',
      },
      {
        id: 'elder_when_noticed',
        text: "When did you first notice something was different?",
        answerType: 'freetext',
        placeholder: 'e.g., "When I visited yesterday" or "My sibling called me this morning"',
        summaryKey: 'when_noticed',
        section: 'What changed',
      },
      {
        id: 'elder_last_normal',
        text: "When were they last their normal self, as far as you know?",
        answerType: 'freetext',
        placeholder: 'e.g., "Sunday when we had dinner" or "I\'m not sure — they live alone"',
        summaryKey: 'last_normal',
        section: 'What changed',
      },
      {
        id: 'elder_baseline_walk',
        text: "Before this, could they walk on their own? How was their mobility?",
        answerType: 'freetext',
        placeholder: 'e.g., "Used a cane but could walk around the house independently"',
        summaryKey: 'baseline_mobility',
        section: 'Functional baseline',
      },
      {
        id: 'elder_baseline_self_care',
        text: "Before this, could they dress, bathe, and feed themselves independently?",
        answerType: 'choice',
        choices: ['Fully independent', 'Needed some help', 'Needed significant help', "I'm not sure"],
        summaryKey: 'baseline_self_care',
        section: 'Functional baseline',
      },
      {
        id: 'elder_baseline_mental',
        text: "Before this, how was their thinking and memory? Could they hold a normal conversation?",
        answerType: 'choice',
        choices: ['Sharp and clear', 'Mild forgetfulness but mostly fine', 'Noticeable memory problems', 'Diagnosed dementia or cognitive decline'],
        summaryKey: 'baseline_cognition',
        section: 'Functional baseline',
      },
      {
        id: 'elder_falls',
        text: "Have they fallen recently?",
        answerType: 'yesno',
        branches: { 'Yes': 'elder_fall_detail', 'No': 'elder_confusion' },
        summaryKey: 'recent_falls',
        section: 'Fall history',
      },
      {
        id: 'elder_fall_detail',
        text: "When did they fall, and what happened? Did they hit their head?",
        answerType: 'freetext',
        placeholder: 'Describe the fall',
        summaryKey: 'fall_detail',
        section: 'Fall history',
      },
      {
        id: 'elder_confusion',
        text: "Are they confused or disoriented in a way that's new or worse than usual?",
        answerType: 'yesno',
        summaryKey: 'new_confusion',
        section: 'Cognitive changes',
      },
      {
        id: 'elder_uti_fever',
        text: "Have they had any burning when urinating, increased urinary frequency, or a fever?",
        answerType: 'yesno',
        summaryKey: 'uti_symptoms',
        section: 'Cognitive changes',
      },
      {
        id: 'elder_breathing',
        text: "Are they breathing faster than usual, or does their breathing seem labored?",
        answerType: 'yesno',
        summaryKey: 'breathing_changes',
        section: 'Cognitive changes',
      },
      {
        id: 'elder_pain',
        text: "Have they complained of any pain — even vaguely? Sometimes described as tiredness or 'just not feeling right.'",
        answerType: 'yesno',
        branches: { 'Yes': 'elder_pain_detail', 'No': 'elder_blood_thinners' },
        summaryKey: 'pain_present',
        section: 'Cognitive changes',
      },
      {
        id: 'elder_pain_detail',
        text: "Where is the pain, and how do they describe it?",
        answerType: 'freetext',
        placeholder: 'What they say and where it hurts',
        summaryKey: 'pain_detail',
        section: 'Cognitive changes',
      },
      {
        id: 'elder_blood_thinners',
        text: "Are they on blood thinners? (e.g., warfarin/Coumadin, Eliquis, Xarelto, Plavix, daily aspirin)",
        answerType: 'choice',
        choices: ['Yes', 'No', "I don't know"],
        summaryKey: 'blood_thinners',
        section: 'Medication changes',
      },
      {
        id: 'elder_med_changes',
        text: "Have any medications been changed recently?",
        answerType: 'yesno',
        branches: { 'Yes': 'elder_med_details', 'No': 'elder_eating' },
        summaryKey: 'med_changes',
        section: 'Medication changes',
      },
      {
        id: 'elder_med_details',
        text: "What medication changed, and when?",
        answerType: 'freetext',
        placeholder: 'What changed and when',
        summaryKey: 'med_change_details',
        section: 'Medication changes',
      },
      {
        id: 'elder_eating',
        text: "How have they been eating and drinking?",
        answerType: 'choice',
        choices: ['Normal', 'Less than usual', 'Barely eating or drinking', "I'm not sure — I haven't been there"],
        summaryKey: 'eating_status',
        section: 'Daily functioning',
      },
      {
        id: 'elder_urination',
        text: "Have they been urinating normally, as far as you know?",
        answerType: 'choice',
        choices: [
          'Yes — seems normal',
          'Less than usual',
          'Barely or not at all in the past day',
          "I don't know",
        ],
        summaryKey: 'urination_status',
        section: 'Daily functioning',
      },
      {
        id: 'elder_living',
        text: "What is their living situation?",
        answerType: 'choice',
        choices: ['Lives alone', 'Lives with spouse/partner', 'Lives with family', 'Assisted living', 'Nursing facility'],
        summaryKey: 'living_situation',
        section: 'Context',
      },
      {
        id: 'elder_concern',
        text: "What worries you most right now?",
        answerType: 'freetext',
        placeholder: 'Your biggest concern',
        summaryKey: 'primary_concern',
        section: 'Your concern',
      },
    ],
  },
  {
    id: 'neurological',
    label: "Can't walk, stand, or move normally",
    description: 'Sudden weakness, numbness, or loss of function in arms or legs',
    icon: '🧠',
    estimateMinutes: 15,
    questions: [
      {
        id: 'neuro_sides',
        text: "Is the weakness or numbness on one side of the body, or in both legs?",
        answerType: 'choice',
        choices: [
          'One side of the body — arm and/or leg, maybe the face',
          'Both legs',
          'All four limbs',
          "I'm not sure",
        ],
        branches: {
          'Both legs': 'neuro_how_arrived',
          'All four limbs': 'neuro_how_arrived',
          "I'm not sure": 'neuro_how_arrived',
        },
        summaryKey: 'weakness_distribution',
        section: 'Where the weakness is',
      },
      {
        id: 'neuro_stroke_face',
        text: "Does their face look uneven or droopy on one side? Ask them to smile if you can.",
        answerType: 'yesno',
        urgentAlert: {
          on: ['Yes'],
          message: "Facial drooping with one-sided weakness can be a sign of a stroke. Stroke treatment is time-critical. Tell the triage nurse now — don't wait to be called back.",
        },
        summaryKey: 'face_droop',
        section: 'Possible stroke signs',
      },
      {
        id: 'neuro_stroke_speech',
        text: "Is their speech slurred, garbled, or are they struggling to find words?",
        answerType: 'yesno',
        urgentAlert: {
          on: ['Yes'],
          message: "Slurred or garbled speech with one-sided weakness can be a sign of a stroke. Stroke treatment is time-critical. Tell the triage nurse now — don't wait to be called back.",
        },
        summaryKey: 'speech_changes',
        section: 'Possible stroke signs',
      },
      {
        id: 'neuro_stroke_vision',
        text: "Have they had sudden vision problems — blurry vision, double vision, or loss of vision in one or both eyes?",
        answerType: 'yesno',
        urgentAlert: {
          on: ['Yes'],
          message: "Sudden vision changes with one-sided weakness can be a sign of a stroke. Stroke treatment is time-critical. Tell the triage nurse now — don't wait to be called back.",
        },
        summaryKey: 'vision_changes',
        section: 'Possible stroke signs',
      },
      {
        id: 'neuro_stroke_last_normal',
        text: "When were they last seen completely normal? Be as exact as you can — this can determine treatment options.",
        answerType: 'freetext',
        placeholder: 'e.g., "8:30 this morning" or "When she went to bed at 11pm"',
        summaryKey: 'last_known_well',
        section: 'Possible stroke signs',
      },
      {
        id: 'neuro_how_arrived',
        text: "How did they get from home to the vehicle?",
        answerType: 'choice',
        choices: [
          'I carried them',
          'I supported them while they walked',
          'They crawled or dragged themselves',
          'They used a walker or cane',
          'They could not move — someone else helped',
        ],
        summaryKey: 'arrival_method',
        section: 'How they got here',
      },
      {
        id: 'neuro_weight_bearing',
        text: "Could they put any weight on their legs at all?",
        answerType: 'yesno',
        summaryKey: 'weight_bearing',
        section: 'How they got here',
      },
      {
        id: 'neuro_wheelchair',
        text: "Was a wheelchair used at the hospital?",
        answerType: 'yesno',
        branches: { 'Yes': 'neuro_wheelchair_source', 'No': 'neuro_last_normal' },
        summaryKey: 'wheelchair_used',
        section: 'How they got here',
      },
      {
        id: 'neuro_wheelchair_source',
        text: "Where did the wheelchair come from?",
        answerType: 'choice',
        choices: [
          'I got it from the hospital entrance',
          'Hospital staff brought it',
          'We brought our own',
          'Someone else got it for us',
        ],
        summaryKey: 'wheelchair_source',
        section: 'How they got here',
      },
      {
        id: 'neuro_last_normal',
        text: "When did they last walk normally without any difficulty?",
        answerType: 'freetext',
        placeholder: 'e.g., "Yesterday morning" or "About a week ago"',
        summaryKey: 'last_normal',
        section: 'When this started',
      },
      {
        id: 'neuro_onset',
        text: "Did the weakness come on suddenly or build up gradually?",
        answerType: 'choice',
        choices: ['Suddenly — within minutes or hours', 'Gradually — over days or weeks', "I'm not sure"],
        summaryKey: 'onset_type',
        section: 'When this started',
      },
      {
        id: 'neuro_doing_when',
        text: "What were they doing when you first noticed they couldn't stand or walk?",
        answerType: 'freetext',
        placeholder: 'Describe what happened',
        summaryKey: 'onset_activity',
        section: 'When this started',
      },
      {
        id: 'neuro_getting_worse',
        text: "Since it started, has their ability to move gotten worse, stayed the same, or improved?",
        answerType: 'choice',
        choices: ['Getting worse', 'About the same', 'Somewhat improved', "I'm not sure"],
        summaryKey: 'progression',
        section: 'When this started',
      },
      {
        id: 'neuro_what_observed',
        text: "What have you watched them try to do, and what happened?",
        answerType: 'freetext',
        placeholder: 'e.g., "She tried to stand from the bed and her legs buckled"',
        summaryKey: 'observed_attempts',
        section: 'What you directly observed',
      },
      {
        id: 'neuro_what_cant_do',
        text: "Right now, what can they do without help — and what can't they do?",
        answerType: 'freetext',
        placeholder: 'e.g., "She can sit up but cannot stand or bear weight"',
        summaryKey: 'current_ability',
        section: 'What you directly observed',
      },
      {
        id: 'neuro_bowel_bladder',
        text: "Have they had any trouble urinating, or any loss of bladder or bowel control?",
        answerType: 'yesno',
        urgentAlert: {
          on: ['Yes'],
          message: 'Loss of bladder or bowel control alongside leg weakness can signal spinal cord compression — an emergency. Tell the triage nurse now.',
        },
        summaryKey: 'bowel_bladder',
        section: 'What you directly observed',
      },
      {
        id: 'neuro_hands_arms',
        text: "Have they mentioned their hands or arms feeling weak, clumsy, or numb? Dropping things, trouble buttoning clothes?",
        answerType: 'yesno',
        summaryKey: 'hand_arm_symptoms',
        section: 'What you directly observed',
      },
      {
        id: 'neuro_neck_pain',
        text: "Have they mentioned neck pain, arm tingling, or numbness recently — even casually?",
        answerType: 'yesno',
        branches: { 'Yes': 'neuro_neck_details', 'No': 'neuro_balance' },
        summaryKey: 'neck_symptoms',
        section: 'Symptoms pointing to a physical cause',
      },
      {
        id: 'neuro_neck_details',
        text: "Can you describe what they've said about the neck pain, tingling, or numbness?",
        answerType: 'freetext',
        placeholder: 'What they told you, in their words',
        summaryKey: 'neck_details',
        section: 'Symptoms pointing to a physical cause',
      },
      {
        id: 'neuro_balance',
        text: "Have they had trouble with balance or coordination recently?",
        answerType: 'yesno',
        summaryKey: 'balance_issues',
        section: 'Symptoms pointing to a physical cause',
      },
      {
        id: 'neuro_fever',
        text: "Have they had a fever, chills, or a recent infection?",
        answerType: 'yesno',
        summaryKey: 'fever_infection',
        section: 'Symptoms pointing to a physical cause',
      },
      {
        id: 'neuro_falls',
        text: "Have they had any recent falls?",
        answerType: 'yesno',
        branches: { 'Yes': 'neuro_falls_detail', 'No': 'neuro_imaging' },
        summaryKey: 'recent_falls',
        section: 'Symptoms pointing to a physical cause',
      },
      {
        id: 'neuro_falls_detail',
        text: "Can you describe the fall(s)? When, where, and what happened?",
        answerType: 'freetext',
        placeholder: 'Describe what happened',
        summaryKey: 'falls_detail',
        section: 'Symptoms pointing to a physical cause',
      },
      {
        id: 'neuro_imaging',
        text: "Has anyone previously suggested imaging of their spine — an MRI, CT scan, or X-ray?",
        answerType: 'yesno',
        branches: { 'Yes': 'neuro_imaging_detail', 'No': 'neuro_medications' },
        summaryKey: 'prior_imaging_suggested',
        section: 'Prior medical context',
      },
      {
        id: 'neuro_imaging_detail',
        text: "What imaging was suggested or ordered? By whom, and has it been done?",
        answerType: 'freetext',
        placeholder: 'e.g., "Dr. Smith ordered a cervical MRI two weeks ago, not done yet"',
        summaryKey: 'imaging_detail',
        section: 'Prior medical context',
      },
      {
        id: 'neuro_medications',
        text: "Are they on any medications? (Especially blood thinners, steroids, or pain medications)",
        answerType: 'freetext',
        placeholder: 'List what you know, or "I\'m not sure"',
        summaryKey: 'medications',
        section: 'Prior medical context',
        skippable: true,
      },
      {
        id: 'neuro_prior_provider',
        text: "Is there a doctor, specialist, or telehealth provider who has been following this problem?",
        answerType: 'freetext',
        placeholder: 'Provider name and type, or "No"',
        skippable: true,
        summaryKey: 'prior_provider',
        section: 'Prior medical context',
      },
    ],
  },
  {
    id: 'seizure',
    label: "They had a seizure or became unresponsive",
    description: 'Shaking, convulsions, staring spells, or found unresponsive',
    icon: '💫',
    estimateMinutes: 9,
    questions: [
      {
        id: 'seiz_witnessed',
        text: "Did you see it happen?",
        answerType: 'yesno',
        branches: { 'Yes': 'seiz_describe', 'No': 'seiz_found' },
        summaryKey: 'witnessed',
        section: 'What happened',
      },
      {
        id: 'seiz_describe',
        text: "Describe exactly what you saw — what their eyes, face, arms, and legs were doing. Your description matters more than you think: you may be the only witness.",
        answerType: 'freetext',
        placeholder: 'What you saw, moment by moment',
        next: 'seiz_duration',
        summaryKey: 'witnessed_description',
        section: 'What happened',
      },
      {
        id: 'seiz_found',
        text: "How did you find them? What did the scene look like?",
        answerType: 'freetext',
        placeholder: 'Position, surroundings, anything unusual nearby',
        summaryKey: 'found_description',
        section: 'What happened',
      },
      {
        id: 'seiz_duration',
        text: "How long did the episode last? Even a rough guess helps.",
        answerType: 'freetext',
        placeholder: 'e.g., "About 2 minutes" — it often feels longer than it was',
        summaryKey: 'duration',
        section: 'During the episode',
      },
      {
        id: 'seiz_over_five',
        text: "Did it last longer than 5 minutes — or did a second one start before they recovered from the first?",
        answerType: 'yesno',
        urgentAlert: {
          on: ['Yes'],
          message: 'A seizure lasting more than 5 minutes, or repeating without recovery, is a medical emergency. Make sure staff know immediately.',
        },
        summaryKey: 'over_five_minutes',
        section: 'During the episode',
      },
      {
        id: 'seiz_features',
        text: "During the episode, what did you notice? Select all that apply.",
        answerType: 'multichoice',
        choices: [
          'Whole body stiffening or jerking',
          'Only one side or one limb moving',
          'Staring blankly — unresponsive with eyes open',
          'Lips or face turning blue',
          'Eyes rolling back',
          'Loss of bladder control',
          'They bit their tongue',
          "None of these / I didn't see it",
        ],
        summaryKey: 'episode_features',
        section: 'During the episode',
      },
      {
        id: 'seiz_after',
        text: "What were they like right after it ended?",
        answerType: 'choice',
        choices: [
          'Confused or groggy for a while',
          'Fell into a deep sleep',
          'Back to normal quickly',
          'Still not back to normal',
          "I wasn't there",
        ],
        summaryKey: 'post_episode_state',
        section: 'After the episode',
      },
      {
        id: 'seiz_head_hit',
        text: "Did they hit their head during the episode — or could they have?",
        answerType: 'yesno',
        summaryKey: 'head_impact',
        section: 'After the episode',
      },
      {
        id: 'seiz_first_time',
        text: "Is this the first episode like this that you know of?",
        answerType: 'yesno',
        branches: { 'Yes': 'seiz_before_episode', 'No': 'seiz_history' },
        summaryKey: 'first_episode',
        section: 'Medical context',
      },
      {
        id: 'seiz_history',
        text: "What is their seizure history? Are they on seizure medication — and have they been taking it?",
        answerType: 'freetext',
        placeholder: 'Diagnosis, medications, and any missed doses',
        summaryKey: 'seizure_history',
        section: 'Medical context',
      },
      {
        id: 'seiz_before_episode',
        text: "What were they doing in the hours before? Any illness, missed medications, alcohol, drugs, or lack of sleep?",
        answerType: 'freetext',
        placeholder: 'Anything unusual leading up to it',
        summaryKey: 'before_episode',
        section: 'Medical context',
      },
      {
        id: 'seiz_pregnancy',
        text: "Is there any chance they could be pregnant? (Seizures during pregnancy can be an emergency)",
        answerType: 'choice',
        choices: ['Yes — possibly', 'No', 'Not applicable'],
        summaryKey: 'pregnancy_possible',
        section: 'Medical context',
      },
      {
        id: 'seiz_concern',
        text: "What worries you most right now?",
        answerType: 'freetext',
        placeholder: 'Your biggest concern',
        summaryKey: 'primary_concern',
        section: 'Your concern',
      },
    ],
  },
  {
    id: 'allergic',
    label: "Allergic reaction",
    description: 'Hives, swelling, or a reaction to food, medication, or a sting',
    icon: '🐝',
    estimateMinutes: 8,
    questions: [
      {
        id: 'all_trigger',
        text: "What do you think caused it — food, a medication, an insect sting, something else? And when were they exposed?",
        answerType: 'freetext',
        placeholder: 'e.g., "Ate shrimp about 30 minutes ago" or "New antibiotic this morning"',
        summaryKey: 'trigger',
        section: 'What happened',
      },
      {
        id: 'all_speed',
        text: "How fast did symptoms appear after exposure?",
        answerType: 'choice',
        choices: ['Within minutes', 'Within an hour', 'Several hours later', "I'm not sure"],
        summaryKey: 'onset_speed',
        section: 'What happened',
      },
      {
        id: 'all_symptoms',
        text: "What symptoms do they have? Select all that apply.",
        answerType: 'multichoice',
        choices: [
          'Hives or an itchy rash',
          'Swelling of the face, lips, or tongue',
          'Throat tightness or trouble swallowing',
          'Trouble breathing or wheezing',
          'Blue, grey, or pale skin or lips',
          'Vomiting or diarrhea',
          'Dizziness or fainting',
          'None of these',
        ],
        urgentAlert: {
          on: ['Swelling of the face, lips, or tongue', 'Throat tightness or trouble swallowing', 'Trouble breathing or wheezing', 'Blue, grey, or pale skin or lips'],
          message: 'These can be signs of anaphylaxis, which can worsen quickly. Tell the triage nurse now — this cannot wait.',
        },
        summaryKey: 'symptoms',
        section: 'Symptoms',
      },
      {
        id: 'all_epi',
        text: "Was an EpiPen (epinephrine) used?",
        answerType: 'choice',
        choices: [
          'Yes — and it helped',
          "Yes — but it didn't help or symptoms came back",
          "No — we have one but didn't use it",
          "No — we don't have one",
        ],
        summaryKey: 'epinephrine_given',
        section: 'What was done',
      },
      {
        id: 'all_other_meds',
        text: "Was anything else given — like Benadryl? What, and when?",
        answerType: 'freetext',
        placeholder: 'e.g., "Benadryl 25mg about 20 minutes ago" or "Nothing"',
        summaryKey: 'other_meds_given',
        section: 'What was done',
        skippable: true,
      },
      {
        id: 'all_prior',
        text: "Have they had allergic reactions before?",
        answerType: 'yesno',
        branches: { 'Yes': 'all_prior_detail', 'No': 'all_concern' },
        summaryKey: 'prior_reactions',
        section: 'Medical context',
      },
      {
        id: 'all_prior_detail',
        text: "To what, and how severe were they?",
        answerType: 'freetext',
        placeholder: 'What triggered them and how bad they got',
        summaryKey: 'prior_reaction_detail',
        section: 'Medical context',
      },
      {
        id: 'all_concern',
        text: "What worries you most right now?",
        answerType: 'freetext',
        placeholder: 'Your biggest concern',
        summaryKey: 'primary_concern',
        section: 'Your concern',
      },
    ],
  },
  {
    id: 'overdose',
    label: "They took something — overdose or poisoning",
    description: 'Known or suspected overdose, wrong medication, or poisoning',
    icon: '💊',
    estimateMinutes: 8,
    questions: [
      {
        id: 'od_what',
        text: "What did they take, if you know? Names of medications or substances — even partial names help.",
        answerType: 'freetext',
        placeholder: 'e.g., "Tylenol and something from an unmarked bottle"',
        summaryKey: 'substance',
        section: 'What was taken',
      },
      {
        id: 'od_amount',
        text: "How much did they take, as best you can tell? Counting pills left in bottles helps.",
        answerType: 'freetext',
        placeholder: 'e.g., "Bottle of 30 was nearly full yesterday, now 6 left"',
        summaryKey: 'amount',
        section: 'What was taken',
      },
      {
        id: 'od_when',
        text: "When did they take it — or when is the last time you know they were okay?",
        answerType: 'freetext',
        placeholder: 'e.g., "Sometime after 9pm" or "She was fine at lunch"',
        summaryKey: 'time_taken',
        section: 'What was taken',
      },
      {
        id: 'od_evidence',
        text: "What did you find? Empty bottles, packaging, notes — bring them with you if you can.",
        answerType: 'freetext',
        placeholder: 'What you found and where',
        summaryKey: 'evidence_found',
        section: 'What was taken',
        skippable: true,
      },
      {
        id: 'od_alcohol',
        text: "Might they have also been drinking alcohol?",
        answerType: 'yesno',
        summaryKey: 'alcohol_involved',
        section: 'What was taken',
      },
      {
        id: 'od_state',
        text: "How are they right now? Select all that apply.",
        answerType: 'multichoice',
        choices: [
          'Awake and talking',
          'Drowsy or hard to wake',
          'Vomiting',
          'Breathing seems slow or shallow',
          'Agitated or confused',
          'Unresponsive',
        ],
        urgentAlert: {
          on: ['Breathing seems slow or shallow', 'Unresponsive'],
          message: 'Slowed breathing or unresponsiveness after taking something is immediately life-threatening. Alert staff right now.',
        },
        summaryKey: 'current_state',
        section: 'How they are now',
      },
      {
        id: 'od_naloxone',
        text: "Was Narcan (naloxone) given?",
        answerType: 'choice',
        choices: ['Yes — they responded', 'Yes — no response', 'No', "I don't know what that is"],
        summaryKey: 'naloxone_given',
        section: 'How they are now',
      },
      {
        id: 'od_intentional',
        text: "Do you believe this was intentional? (The provider needs to know — it changes the care they provide)",
        answerType: 'choice',
        choices: ['Yes', 'No — accidental', "I don't know"],
        summaryKey: 'intentional',
        section: 'Context the provider needs',
      },
      {
        id: 'od_usual_meds',
        text: "What medications do they normally take, if you know?",
        answerType: 'freetext',
        placeholder: 'List what you know, or "I\'m not sure"',
        summaryKey: 'usual_medications',
        section: 'Context the provider needs',
        skippable: true,
      },
      {
        id: 'od_concern',
        text: "What worries you most right now?",
        answerType: 'freetext',
        placeholder: 'Your biggest concern',
        summaryKey: 'primary_concern',
        section: 'Your concern',
      },
    ],
  },
  {
    id: 'psychiatric_organic',
    label: "Something feels different this time",
    description: 'They have a psychiatric history but this seems physical — not their usual episode',
    icon: '⚡',
    estimateMinutes: 12,
    questions: [
      {
        id: 'psych_baseline',
        text: "What does a typical episode look like for them? Briefly describe their usual pattern.",
        answerType: 'freetext',
        placeholder: 'What their usual episodes are like',
        summaryKey: 'baseline_episodes',
        section: "What's different this time",
      },
      {
        id: 'psych_different',
        text: "What is different about what's happening right now?",
        answerType: 'freetext',
        placeholder: 'What made you think this time is different',
        summaryKey: 'what_is_different',
        section: "What's different this time",
      },
      {
        id: 'psych_physical_symptoms',
        text: "Have you noticed any physical symptoms — things that don't fit their usual psychiatric picture?",
        answerType: 'freetext',
        placeholder: 'e.g., "She keeps saying her legs feel heavy" or "He\'s stumbling when he walks"',
        summaryKey: 'physical_symptoms',
        section: 'Physical symptoms you\'ve noticed',
      },
      {
        id: 'psych_new_complaints',
        text: "Have they mentioned any new physical complaints recently — pain, numbness, weakness, vision changes, headaches?",
        answerType: 'yesno',
        branches: { 'Yes': 'psych_complaint_details', 'No': 'psych_speech' },
        summaryKey: 'new_complaints',
        section: 'Physical symptoms you\'ve noticed',
      },
      {
        id: 'psych_complaint_details',
        text: "What physical complaints have they mentioned?",
        answerType: 'freetext',
        placeholder: 'In their words, what they\'ve told you',
        summaryKey: 'complaint_details',
        section: 'Physical symptoms you\'ve noticed',
      },
      {
        id: 'psych_speech',
        text: "Have you noticed any changes in how they speak — slurring, struggling for words, or talking differently than usual?",
        answerType: 'yesno',
        summaryKey: 'speech_changes',
        section: 'Physical symptoms you\'ve noticed',
      },
      {
        id: 'psych_gait',
        text: "Have you noticed them stumbling, shuffling, or moving differently than usual?",
        answerType: 'yesno',
        summaryKey: 'gait_changes',
        section: 'Physical symptoms you\'ve noticed',
      },
      {
        id: 'psych_behavior_change',
        text: "Have you noticed other changes in how they eat, sleep, or function day-to-day — beyond their psychiatric symptoms?",
        answerType: 'freetext',
        placeholder: 'Changes you\'ve observed in daily functioning',
        summaryKey: 'functional_changes',
        section: 'Behavior changes vs. baseline',
      },
      {
        id: 'psych_cognitive',
        text: "Have you noticed confusion, memory problems, or difficulty finding words that's new or unusual for them?",
        answerType: 'yesno',
        summaryKey: 'cognitive_changes',
        section: 'Behavior changes vs. baseline',
      },
      {
        id: 'psych_med_changes',
        text: "Have any medications been started, stopped, or changed recently?",
        answerType: 'yesno',
        branches: { 'Yes': 'psych_med_details', 'No': 'psych_recent_illness' },
        summaryKey: 'med_changes',
        section: 'Recent changes',
      },
      {
        id: 'psych_med_details',
        text: "What medication changed, and when?",
        answerType: 'freetext',
        placeholder: 'Medication name, what changed, and when',
        summaryKey: 'med_change_details',
        section: 'Recent changes',
      },
      {
        id: 'psych_recent_illness',
        text: "Have they had a recent illness, infection, fall, or injury?",
        answerType: 'yesno',
        branches: { 'Yes': 'psych_illness_detail', 'No': 'psych_head_injury' },
        summaryKey: 'recent_illness',
        section: 'Recent changes',
      },
      {
        id: 'psych_illness_detail',
        text: "What happened?",
        answerType: 'freetext',
        placeholder: 'Describe the illness, fall, or injury',
        summaryKey: 'illness_detail',
        section: 'Recent changes',
      },
      {
        id: 'psych_head_injury',
        text: "Have they hit their head recently — even a minor bump?",
        answerType: 'yesno',
        summaryKey: 'recent_head_injury',
        section: 'Recent changes',
      },
      {
        id: 'psych_substances',
        text: "Have they used alcohol or drugs recently — or suddenly stopped after regular use?",
        answerType: 'choice',
        choices: [
          'Yes — used recently',
          'Yes — recently stopped or cut back',
          'No',
          "I don't know",
        ],
        summaryKey: 'substance_use',
        section: 'Recent changes',
      },
      {
        id: 'psych_fever',
        text: "Have they had a fever or any signs of infection recently?",
        answerType: 'yesno',
        summaryKey: 'fever_infection',
        section: 'Recent changes',
      },
      {
        id: 'psych_psych_history',
        text: "What psychiatric diagnoses are in their chart? (This helps the provider understand what is and isn't their baseline)",
        answerType: 'freetext',
        placeholder: 'e.g., "Anxiety and PTSD" or "Bipolar disorder"',
        summaryKey: 'psych_diagnoses',
        section: 'Context the provider needs',
      },
      {
        id: 'psych_concern',
        text: "What is your biggest concern right now — the thing you most want the provider to take seriously?",
        answerType: 'freetext',
        placeholder: 'What you are most worried about',
        summaryKey: 'primary_concern',
        section: 'Context the provider needs',
      },
    ],
  },
  {
    id: 'general',
    label: "Something else is wrong",
    description: "Doesn't fit the categories above? Your observations still matter — start here",
    icon: '📋',
    estimateMinutes: 12,
    questions: [
      {
        id: 'gen_what_happened',
        text: "In your own words, what's wrong? What made you decide to come to the ER?",
        answerType: 'freetext',
        placeholder: 'Describe what brought you in',
        summaryKey: 'what_happened',
        section: 'What happened',
      },
      {
        id: 'gen_when_started',
        text: "When did this start?",
        answerType: 'freetext',
        placeholder: 'e.g., "Two days ago" or "Suddenly, about an hour ago"',
        summaryKey: 'onset_time',
        section: 'Timeline',
      },
      {
        id: 'gen_onset',
        text: "Did it come on suddenly or gradually?",
        answerType: 'choice',
        choices: ['Suddenly — within minutes or hours', 'Gradually — over days or weeks', 'It comes and goes', "I'm not sure"],
        summaryKey: 'onset_type',
        section: 'Timeline',
      },
      {
        id: 'gen_progression',
        text: "Since it started, has it changed?",
        answerType: 'choice',
        choices: ['Getting worse', 'About the same', 'Getting better', 'It fluctuates', "I'm not sure"],
        summaryKey: 'progression',
        section: 'Timeline',
      },
      {
        id: 'gen_observed',
        text: "What have you personally seen or noticed? Specific observations — things you watched happen — carry the most weight.",
        answerType: 'freetext',
        placeholder: 'e.g., "I watched him try to get up twice and he couldn\'t"',
        summaryKey: 'observations',
        section: 'What you observed',
      },
      {
        id: 'gen_baseline',
        text: "How is this different from their normal? What can't they do now that they could before?",
        answerType: 'freetext',
        placeholder: 'What has changed compared to their usual self',
        summaryKey: 'baseline_change',
        section: 'What you observed',
      },
      {
        id: 'gen_pain',
        text: "Are they in pain?",
        answerType: 'yesno',
        branches: { 'Yes': 'gen_pain_detail', 'No': 'gen_fever' },
        summaryKey: 'pain_present',
        section: 'Other symptoms',
      },
      {
        id: 'gen_pain_detail',
        text: "Where is the pain, and how bad does it seem?",
        answerType: 'freetext',
        placeholder: 'Location and severity, in their words if possible',
        summaryKey: 'pain_detail',
        section: 'Other symptoms',
      },
      {
        id: 'gen_fever',
        text: "Have they had a fever?",
        answerType: 'yesno',
        summaryKey: 'fever',
        section: 'Other symptoms',
      },
      {
        id: 'gen_pregnancy',
        text: "Is there any chance they could be pregnant?",
        answerType: 'choice',
        choices: ['Yes — possibly', 'No', 'Not applicable'],
        summaryKey: 'pregnancy_possible',
        section: 'Other symptoms',
      },
      {
        id: 'gen_function',
        text: "How are they eating, drinking, and sleeping?",
        answerType: 'choice',
        choices: ['Normal', 'Somewhat less than usual', 'Barely at all', "I'm not sure"],
        summaryKey: 'daily_function',
        section: 'Daily functioning',
      },
      {
        id: 'gen_urination',
        text: "Have they been urinating normally, as far as you know?",
        answerType: 'choice',
        choices: [
          'Yes — seems normal',
          'Less than usual',
          'Barely or not at all in the past day',
          "I don't know",
        ],
        summaryKey: 'urination_status',
        section: 'Daily functioning',
      },
      {
        id: 'gen_conditions',
        text: "Do they have any medical conditions the provider should know about?",
        answerType: 'freetext',
        placeholder: 'e.g., "Diabetes and high blood pressure" or "None that I know of"',
        summaryKey: 'conditions',
        section: 'Medical context',
        skippable: true,
      },
      {
        id: 'gen_medications',
        text: "What medications do they take, if you know? Any recent changes?",
        answerType: 'freetext',
        placeholder: 'List what you know, or "I\'m not sure"',
        summaryKey: 'medications',
        section: 'Medical context',
        skippable: true,
      },
      {
        id: 'gen_happened_before',
        text: "Has anything like this happened before?",
        answerType: 'yesno',
        branches: { 'Yes': 'gen_before_detail', 'No': 'gen_concern' },
        summaryKey: 'happened_before',
        section: 'Medical context',
      },
      {
        id: 'gen_before_detail',
        text: "What happened last time? Was it evaluated?",
        answerType: 'freetext',
        placeholder: 'What happened and what was found',
        summaryKey: 'prior_episode_detail',
        section: 'Medical context',
      },
      {
        id: 'gen_concern',
        text: "What is your biggest concern — the thing you most want the provider to take seriously?",
        answerType: 'freetext',
        placeholder: 'What you are most worried about',
        summaryKey: 'primary_concern',
        section: 'Your concern',
      },
    ],
  },
];

export function getCategoryById(id: string): Category | undefined {
  return categories.find(c => c.id === id);
}
